name = "mattlones-site"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mattlones-db"
database_id = "placeholder-create-via-wrangler-d1-create"

[[kv_namespaces]]
binding = "SESSIONS"
id = "placeholder-create-via-wrangler-kv-create"
